default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  port: 5432
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: photograms_development
  pool: 13
  username: postgres
  password: t8mU9F123QWE

test:
  <<: *default
  host: localhost
  encoding: utf8
  reconnect: false
  port: 5432
  username: postgres
  password: t8mU9F123QWE
  database: photograms_test

production:
  <<: *default
  host: 13.229.249.74
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  username: postgres
  password: t8mU9F123QWE
  database: photograms_production
